### PR TITLE
Adds ability to apply facets in GraphQL

### PR DESCRIPTION
**Pull request by JPrevost**
Our initial GraphQL implementation was intended as experiemental so it did not incldue the ability to apply facets.

As we start to consider whether we will move to GraphQL fully or stay with REST, it seemed worthwhile to consider how working with facets would feel in GraphQL both in terms of consuming the data and writing the code.

https://mitlibraries.atlassian.net/browse/DISCO-60

#### How can a reviewer manually see the effects of these changes?

Using the GraphQL Playground in this PR, you should note the Docs have been updated to reflect the new ability to optionally apply facets. Some facets, such as Subject allow an array of Strings and others just allow Strings.

An example starting point might be:

```
{
  search(searchterm: "spaceflight",
    	format: ["Print volume"]
  	) {
    hits
    aggregations {
    	source {
        key
        docCount
      }
      languages {
        key
        docCount
      }
      contributors {
        key
        docCount
      }
      contentFormat {
        key
        docCount
      }
      subjects {
        key
        docCount
      }
      literaryForm {
        key
        docCount
      }
    }
    records {
      source
      title
      contentType
      format
      contributors {
        kind
        value
      }
      subjects
      literaryForm
      languages
    }
  }
}
```

#### What are the relevant tickets?

- https://mitlibraries.atlassian.net/browse/DISCO-60

#### Requires Database Migrations?
NO

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by JPrevost** [comment]
A separate commit will follow with tests but I wanted to get some feedback as-is.

**Comment by JPrevost** [comment]
There is inconsistent naming for `format` versus `contentFormat` which I think I'll open a separate ticket on.

**Comment by JPrevost** [comment]
@matt-bernhardt I'm seeing the same behavior. I swear this worked at some point ;). I'll try to figure out what broke between then and now and update. Thanks.

**Review by jazairi — APPROVED** [review]
Sorry, forgot to sign off on this yesterday afternoon. Following the latest commit, faceting works for me on a few test queries (languages, format, literary form, subjects), and the tests pass. :shipit:

**Review by matt-bernhardt — APPROVED** [review]
This looks good to me as well. I agree with resolving the conflict between `format` and `contentFormat` when we get a chance.

:shipit:

**Pull request merged**
